name: inventory-ci

on:
  pull_request:
    branches: [main]
    paths:
      - 'Src/Inventory/**'
      - '.github/workflows/inventory-ci.yml'

jobs:
  ci:
    uses: ./.github/workflows/dotnet-ci-template.yml
    with:
      service-path: Src/Inventory/Inventory.sln