name: orders-ci

on:
  pull_request:
    branches: [main]
    paths:
      - 'Src/Orders/**'
      - '.github/workflows/orders-ci.yml'
  push:
    branches: [main]
    paths:
      - 'Src/Orders/**'

jobs:
  ci:
    uses: ./.github/workflows/dotnet-ci-template.yml
    with:
      service-path: Src/Orders 